config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "requests#dashboard"
  match '/dashboard' => 'requests#dashboard', as: 'user_dashboard', via:[:get]

  match '/:trap_id' => 'requests#index', as: 'main_dashboard', via:[:get]
  match '/:trap_id' => 'requests#destroy', via: [:delete]
  match '/:trap_id' => 'requests#update', via:[:put]
  match '/:trap_id' => 'requests#create', via:[:post]
  match '/:trap_id/requests' => 'requests#display_requests_listing', :as  => 'display_requests_listing', via:[:get]
  match '/:trap_id/requests/:id' => 'requests#show', as: 'display_request', via:[:get]

  match '/requests/fetch_user_requests' => 'requests#fetch_user_requests', :via => [:post], :format => :js

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :remote_ip, :request_method, :scheme
  serialize :cookies
  serialize :headers

  def self.get_latest_requests(trap_id, request_id)
    user = User.get_user_info(trap_id)
    user.requests.where('id > ?', request_id).order('created_at DESC') rescue nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :email, use: :slugged
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests

  def self.get_user_requests(trap_id)
    user = get_user_info(trap_id)
    user.requests.order('created_at DESC') rescue nil
  end

  def self.get_user_info(trap_id)
    self.friendly.find(trap_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    flash[:notice] = 'sign in successful.'
    stored_location_for(resource) || main_dashboard_path(resource)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_user!, :only => [:dashboard, :display_requests_listing]
  skip_before_filter  :verify_authenticity_token, except: [:index, :show, :dashboard, :display_requests_listing]

  def index
    request_flag = add_request_details
    respond_to do |format|
      format.html
      format.json {
        if request_flag
          render nothing: true, status: :ok
        else
          render nothing: true, status: :internal_server_error
        end
      }
    end
  end

  def show
    begin
      @request = current_user.requests.find(params[:id])
    rescue => exception
      redirect_to display_requests_listing_url
    end
  end

  def create
    request_flag = add_request_details
    if request_flag
      render nothing: true, status: :ok
    else
      render nothing: true, status: :internal_server_error
    end
  end

  def update
    request_flag = add_request_details
    if request_flag
      render nothing: true, status: :ok
    else
      render nothing: true, status: :internal_server_error
    end
  end

  def destroy
    request_flag = add_request_details
    if request_flag
      render nothing: true, status: :ok
    else
      render nothing: true, status: :internal_server_error
    end
  end

  def dashboard
  end

  def display_requests_listing
    @users_requests = User.get_user_requests(params[:trap_id])
  end

  def fetch_user_requests
    max_id = params[:id]
    @user_requests = Request.get_latest_requests(current_user.slug, max_id)
    @max = @user_requests.first.id rescue nil
    render partial: '/requests/fetch_request', layout: false
  end

  private

  def add_request_details
    begin
      user = User.get_user_info(params[:trap_id])
      req = Request.new(user_id: user.id,
                        remote_ip: request.remote_ip,
                        request_method: request.request_method,
                        scheme:request.scheme,
                        query_string: request.query_string.to_s,
                        query_params: request.query_parameters.to_s,
                        cookies: request.cookies,
                        headers: request.headers.env.to_s)
      req.save ? true : false
    rescue => exception
      puts "Exception details: #{exception.message.to_s}"
      flag = false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
  def get_max_request(requests)
    requests.first.id rescue 0
  end
  def get_user_slug(request)
    request.user.slug
  end
end

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Product CRM</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
      <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RequestsTrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Requests Trap App</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/requests/_fetch_request.html.erb
<%
   counter = 0
   @user_requests.each_with_index do |request, index|
     counter = request.id if index == 0
%>
  <tr>
    <td><%= request.created_at.strftime("%m/%d/%Y %I:%M%p") %></td>
    <td><%= request.remote_ip %></td>
    <td><%= request.request_method %></td>
    <td><%= link_to 'view details', display_request_path(trap_id: get_user_slug(request), id: request.id) %></td>
  </tr>
<% end %>
<%= javascript_tag do %>
  window.max = '<%= raw @max %>';
<% end %>
<div id="next_max" style="display: none;"><%= @max %></div>

app/views/requests/dashboard.html.erb
<h1>User Dashboard</h1>
<h2>Instructions</h2>
<p>
  Use the following URL for external WebService utilization.<br/>
  <%= link_to "http://requests-trap-app.herokuapp.com/#{current_user.slug}" %>
</p>
<h2>
  Request Listing
</h2>
<div>
  <%= link_to 'Show Request Listing', display_requests_listing_path(trap_id: current_user.slug) %>
</div>

app/views/requests/display_requests_listing.html.erb
<h3 xmlns="http://www.w3.org/1999/html">Requests Listing</h3>
<table class="table table-bordered" cellspacing="0" width="100%" id="requests_listing">
  <thead>
  <tr>
    <th>Request Date</th>
    <th>Remote IP</th>
    <th>Request Method</th>
    <th>Action</th>
  </tr>
  </thead>
  </tbody>

  <% @users_requests.each do |request| %>
    <tr>
      <td><%= request.created_at.strftime("%m/%d/%Y %I:%M%p") %></td>
      <td><%= request.remote_ip %></td>
      <td><%= request.request_method %></td>
      <td><%= link_to 'view details', display_request_path(id: request.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div style="display: none;" id="max_request_id"><%= get_max_request(@users_requests) %></div>

app/views/requests/index.html.erb
<%= link_to 'Show Request Listing', display_requests_listing_path(trap_id: params[:trap_id]) %>

app/views/requests/show.html.erb
<h3>Displaying Request (Trap-ID: <%= current_user.slug %>)</h3>
<table class="table table-striped">
  <tbody>
  <tr><td>Request Date:</td><td><%= @request.created_at.strftime("%m/%d/%Y %I:%M%p") %></td></tr>
  <tr><td>Remote IP:</td><td><%= @request.remote_ip %></td></tr>
  <tr><td>Request Method:</td><td><%= @request.request_method %></td></tr>
  <tr><td>Scheme:</td><td><%= @request.scheme %></td></tr>
  <tr><td>Query String:</td><td><%= @request.query_string %></td></tr>
  <tr><td>Query Parameters:</td><td><%= @request.query_params %></td></tr>
  <tr><td>Cookies:</td><td><%= @request.cookies.as_json %></td></tr>
  <tr><td>Headers:</td><td><%= @request.headers %></td></tr>
  <tr><td><%= link_to 'Back', display_requests_listing_path %></td><td></td></tr>
  </tr>
  </tbody>
</table>